# Задание 1

In [34]:
import numpy as np

In [14]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [16]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

# Задание 2

In [18]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

In [30]:
a_centered_sp = np.dot(a_centered.T[0],a_centered.T[1])/4
a_centered_sp

2.0

# Задание 4

In [36]:
a_centered_sp2 = np.cov(a.T)
a_centered_sp2[0][1]

2.0